### ISSUE TITLE
wx.createPage is not a function

### ISSUE THREAD

**Issue by jiereal** [maichong/labrador#1]
我在Labrador init 之后尝试运行代码 console 打印出错误
`
TypeError: wx.createPage is not a function
    at index.js:20
    at require (WAService.js:2)
`

**Comment by liangxingchen** [comment]
请升级项目中的labrador 和 全局的 labrador-cli 至0.3.x 版本，然后参照 https://github.com/maichong/labrador/blob/master/README.md 升级你的项目代码
