### ISSUE TITLE
labrador 的 redux 绑定库

### ISSUE THREAD

**Issue by eyasliu** [maichong/labrador#11]
前段时间有人根据 react-redux 项目改造写了一个小程序[redux绑定库](https://github.com/charleyw/wechat-weapp-redux)，由于 labrador 特殊性无法直接使用，于是我fork后继续改造，使其适应了labrador

项目地址： https://github.com/eyasliu/wechat-weapp-redux
例子：https://github.com/eyasliu/wechat-app-music

**Comment by mdsb100** [comment]
不想用react-redux怎么办

**Comment by liangxingchen** [comment]
请使用 https://github.com/maichong/labrador-redux
