### ISSUE TITLE
dist 目标文件太大

### ISSUE THREAD

**Issue by kamidox** [maichong/labrador#15]
目前 demo 编译出来压缩完是 568 KB。而微信小程序大小限制是 1 MB。

这个应该是最大的问题，否则这个工具会成为微信小程序开发的必备工具和流水线了。

**Comment by liangxingchen** [comment]
这个问题根本不是问题，我们最新版的Labrador会强力压缩JS，最近两天就会正是发布。
另外，你这里所指的568KB，实际上不会有这么大，没猜错的话，你的磁盘分区的块大小是4K，那么每一个小文件哪怕只有1B大小，也会在磁盘上占用4K空间，所以你这里的568KB实际上是磁盘上分配了142个块所产生的磁盘占用，但是所有文件的实际大小总和会远远低于568KB，因为目前npm目录下会有很多很小的文件。
![image](https://cloud.githubusercontent.com/assets/13582828/20427055/fa2462ae-adbc-11e6-84bc-d58a16c56a40.png)
像这个截图中，磁盘占用766KB，但是实际文件总和是308KB。

另外新版本中的强力压缩，会将所有JS打包成一个文件，效果是这样的：
![image](https://cloud.githubusercontent.com/assets/13582828/20427109/4e0e67d4-adbd-11e6-86ef-ddf15134e500.png)
![image](https://cloud.githubusercontent.com/assets/13582828/20427110/526a572a-adbd-11e6-88b2-ecc7517fb273.png)

**Comment by kamidox** [comment]
嗯，所有的外部依赖打包成一个文件，类似 React 的 bundle.js 这样确实可以减小文件尺寸。

另外一方面，是否可以尽量减少运行时外部库的依赖？
ES6/ES7 的相关语法可以靠 babel 在编译期搞定。一些新特性如 Promise, await/async 等可以靠 polyfills 代码搞定。
less 转 wxss 也可以在编译期搞定。剩下的就是组件复用，页面即组件的这些实现。如果这些优化一下是否也可以减少 dist 文件的大小？

因为我看目前的环境，编译出来的微信小程序里，npm 目录下的 core-js 占了大部分的文件空间，是否真的需要 core-js 里的所有功能呢？

无论如何，这个工具把大家从微信小程序原生的蹩脚的开发方法里解救了出来，就像大家原来都开着宝马上班，突然有一天给你一辆自行车上下班，而且还是90年代的那种大横梁男式老爷车。欲哭无泪。直到 labrador 出现，救大家于水火。

这段话会不会太肉麻了。哈哈，期待你的新版本。

**Comment by bachaxianren** [comment]
根据文档labrador create demo,我dist目录1.28M，在微信开发工具中导入dist，页面请求有363个，大小1.8M，这都超出1M了，我用labrador minify-js 压缩js大小还是超1M。我是新手，请问这问题是什么情况，该如何解决
