### ISSUE TITLE
Page 和 Component 的 onShow 等生命周期方法

### ISSUE THREAD

**Issue by i-tengfei** [maichong/labrador#7]
Page 和 Component 还是有区别的，目前 Component 也有 onShow\onHide 等方法，但目前这些方法都是直接使用的 Page 的执行时机，会在使用上造成误导。

```
<view>
    <block wx:if="{{shown}}">
        <component key="test" />
    </block>
</view>
```

类似于上面的结构，即便shown为false，component 的 onShow 方法也会被调用。
而且现有的条件来看，好像没有办法监测到组件的运行状态。
建议不如直接去掉这些方法，或者修改一下名称，避免造成误导。

**Comment by liangxingchen** [comment]
如果去掉这些方法或者更换名称，那么将违背页面也是组件的思想
